### ISSUE TITLE
Contao 4.4 / PHP >= 7.1

### ISSUE THREAD

**Issue by Schmidty2** [OMOSde/om_searchkeys#3]
Hallo,
Ist eine Version für Contao >= 4.4 und PHP >= 7.1 geplant?
Eine finanzielle Unterstützung wäre möglich.

**Comment by OMOSde** [comment]
Hi,

ich habe bereits eine implementierte Version für Contao 4.4. Ich bin mir gerade nur nicht sicher, inwieweit diese komplett bzw. getestet ist. Ich würde dies am Wochenende mal schauen.

Bitte erinnern, falls ich es vergesse! :-)

**Comment by OMOSde** [comment]
Es ist von der alten Version nicht viel übrig. Ich habe die vergangenen Tage genutzt und quasi ein Rewrite des Moduls für Contao 4.4+ erstellt.

Siehe https://github.com/OMOSde/contao-om-search
